apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcolor
  namespace: argocd
spec:
  destination:
    namespace: novosga
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./
    repoURL: https://github.com/marcusjava/kubernetes_sga.git
    targetRevision: HEAD
  syncPolicy: {}
