apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: novosga
  namespace: argocd
spec:
  destination:
    namespace: novosga
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./
    repoURL: https://github.com/marcusjava/kubernetes_sga.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - "CreateNamespace=true"
    automated:
      selfHeal: true
      prune: true
